### ISSUE TITLE
bmake malformed conditional error

### ISSUE THREAD

**Issue by Phrunsys** [Stichting-MINIX-Research-Foundation/minix#331]
![Screenshot_2022-02-09_14-17-47](https://user-images.githubusercontent.com/97553855/153274110-c4103f74-25d8-497c-8615-c36f8c92bf37.png)

**Comment by petershh** [comment]
Hello,

Which version of debian and bmake are you using?

**Comment by Phrunsys** [comment]
Debian 11 but I also tried on debian 8. Everything failed

**Comment by Phrunsys** [comment]
i tried changing my make. i tried on debian 11 x86-64
then debian 8 i386 
using the latest make and bmake
all failed

**Comment by petershh** [comment]
Have you tried building with with build.sh?

**Comment by Phrunsys** [comment]
no, Tell me how i do it now

**Comment by petershh** [comment]
https://wiki.minix3.org/doku.php?id=developersguide:crosscompiling

**Comment by Phrunsys** [comment]
error:
POZIX regex.h is required

**Comment by petershh** [comment]
Did you install build dependencies?

**Comment by Phrunsys** [comment]
Yes

**Comment by petershh** [comment]
Can you please attach full output of build.sh invocation?

**Comment by Phrunsys** [comment]
How do I compile only the basic utilities because it seems I'm downloading
Llvm and more other tools during compilation
Do I have to close the network ?

**Comment by petershh** [comment]
Build process involves compiling cross-compiler which in turn will build Minix system. This is expected behaviour.

**Comment by Phrunsys** [comment]
So why not GCC ?

**Comment by petershh** [comment]
Because of licensing issues - gcc is distributed under GNU GPL, and Minix is BSD licensed

**Comment by stux2000** [comment]
Hi Phrunsys,

Thank you for your interest in Minix.  To answer your question briefly: gcc isn't used primarily for licensing but also some technical reasons.  However,  since this is the github issues system, I'd request that the discussion centers around your original bmake issue.  

That said, this issue seems to center more about the usage of bmake and how to build parts of Minix than a specific problem with the Minix build tools.  Instead, I would highly recommend posting any questions related to this matter on the google groups mailing list: https://groups.google.com/g/minix3

Thanks,
-stux

**Comment by Phrunsys** [comment]
I get but it's taking longer cross compiling.

**Comment by Phrunsys** [comment]
Ok. So if I get clang locally installed before building minix. Do I save
trouble and time of building Clang ?

**Comment by petershh** [comment]
1) No
2) As stux said, please post general questions on building minix in minix google group. I think this bmake issue is resolved and issue may be closed.

**Comment by Phrunsys** [comment]
The malformed conditional issue was resolved by;  for var in ${list}
Not; for var in list
As it's how it comes written from the repo. Kindly update those loops.

**Comment by dcvmoole** [comment]
> Kindly update those loops.

Hello. It appears you are trying to report a bug for MINIX 3.2.1. Can you also reproduce the issue with the latest MINIX version (3.4.0-rc6)? MINIX 3.2.1 has been released already, a long time ago, and is no longer subject to bug fixes.

**Comment by Phrunsys** [comment]
That malformed issues still stands when you directly call bmake. Cross
Compilation via script works but a manual ivokation of bmake from the
source tree fails

**Comment by dcvmoole** [comment]
> That malformed issues still stands when you directly call bmake.

What made you invoke bmake directly from the cross-compilation host system? Is there documentation that lists that as a step to perform? If so, could you please link that here?
